spring:
   application: 
      name: springboot-provider-user-service
   datasource:
      name:shop
      url:jdbc:mysql://121.42.185.68:3306/shop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username:root
      password:wazll1314 
      type:com.alibaba.druid.pool.DruidDataSource
      driver-class-name:com.mysql.jdbc.Driver
      filters:stat
      maxActive:20
      initialSize:1
      maxWait:60000
      minIdle:1
      timeBetweenEvictionRunsMillis:6000
      minEvictableIdleTimeMillis:300000
      validationQuery:select 'x'
      testWhileIdle:true
      testOnBorrow:false
      testOnReturn:false
      poolPreparedStatements:true
      maxOpenPreparedStatements:20
   mybatis:
      mapperLocations:classpath:mapper/*.xml
      typeAliasesPackage:com.jiujichina.model 
   eureka: 
    client: 
     serviceUrl: 
         defaultZone: http://121.42.185.68:8761/eureka/
         register-with-eureka: false
         fetch-registry: false
    instance: 
      prefer-ip-address: true
       